hal_io:

  # I/O main loop publish rate in Hz
  update_rate: 10

  # Pin definitions
  #
  # output_pins: are read from a topic (default) or service

  # HAL pins are named hal_io.<pin_name>
  # HAL pins types are BIT, FLOAT, S32, U32

  # pins: a hash/dict of HAL pins, can be all HAL types
  # - HAL pin types are BIT, FLOAT, S32, U32
  # - HAL pin directions are OUT, IN, IO
  # - ROS publish topic, used for all HAL pins
  # - ROS subscribe topic, used for HAL IN and IO pins
  # HAL publish and subscribe topics are implicitly set to the HAL pin name per default
  subscribe_pins:
    # subscribe_pins values read from ROS topic and copied to HAL
    # output pin
    float_out:
      type: FLOAT
      # Explicitly set subscribe topic name
      sub: hal_io/float_out
    bool_out:
      type: BIT
    int_out:
      type: S32
    uint_out:
      type: U32
  publish_pins:
    # publish_pins values read from HAL input pin and published to ROS
    # topic
    float_in:
      type: FLOAT
      # Explicitly set publish topic name
      pub: hal_io/float_in
    bool_in:
      type: BIT
      # Explicitly set HAL pin direction
      direction: IN
    int_in:
      type: S32
    uint_in:
      type: U32
    float_io:
      type: FLOAT
      # Set HAL IO pin
      direction: IO
  service_pins:
    bool_svc:
      type: BIT
      # Set HAL IO pin
      direction: IO
    int_svc:
      type: S32
    uint_svc:
      type: U32
    float_svc:
      type: FLOAT

hal_mgr:
  hal_files:
    # Load a HAL file that inits a thread
    - hal_io.hal
