# Package name
package: hal_ros_control

# Project name for human-readable output
projectName: hal_ros_control

# Package-specific command to run during image build before installing
#    build deps (default: none)
scriptPreCmd: .github/docker/script_pre.sh

# Package-specific command to run during image build after installing
#    build deps (default: none)
# scriptPostCmd: .github/docker/mypackage_script_post.sh

# Package-specific command to run in container before package build
#    (default: none)
configureSourceCmd: .github/docker/configure_source.sh

# Files to copy into Docker build context "files" directory
dockerBuildContextFiles:
  - hal_hw_interface/package.xml

# Non-standard package subdirectory (default: `.`)
sourceDir: hal_hw_interface

# Location of `debian/` packaging directory (default: `./debian`)
debian_dir: hal_hw_interface/debian

# Docker image name and tag template (default:
#    `@PACKAGE@-@DISTRIBUTION@-builder` and `@RELEASE@_@ARCHITECTURE@`)
#
# DANGER: Changing imageNameFmt or imageTagFmt will mean a new Docker
#    image name!  Public Docker images in GitHub Packages cannot be
#    deleted, every change will stay visible 'forever' in form of old
#    packages
#
#imageNameFmt: @PACKAGE@-@VENDOR@-builder
#imageTagFmt: @RELEASE@_@ARCHITECTURE@

# Docker image label prefix (default: `io.machinekit.${{package}}`)
#label_prefix: io.machinekit.mypackage

# Cloudsmith repo slug, if not the same as `package`
cloudsmith_repo_slug: hal_ros_control

osDistros:
  # List of Debian and Ubuntu OS version configuration data
  - baseImage: ubuntu:focal
    codename: Focal
    vendor: Ubuntu
    release: 20.04

allowedCombinations:
  # Supported combinations of `release` : architecture
  #
  # amd64:
  - architecture: amd64
    release: 20.04
